### ISSUE TITLE
Discussion on Language schema

### ISSUE THREAD

**Issue by johanneshiry** [coverified/platform_backend#4]
As for now, the Language only consists of a UUID as well as an id. 

For simpler and more straight forward handling in the backend we need to decide if we either 

- establish the convention that the id must follow [ISO-639-1 rules](https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes) (and subsequently convert it to a human readable representation on the frontend side)
- or let id be a "human readable" string and add another field that maps the human readable string to the corresponding ISO-639-1 representation

**Comment by schliflo** [comment]
I think the ISO-639-1 string would be human readable enough already - no mapping/translation needed. I'd settle on that for now and add new languages based on that convention.

**Comment by johanneshiry** [comment]
I think we can close this now then?
